-d /home/harbaum/projekte/private_stuff/mistlite/board/mistle_gw3a_20/tests/leds/impl/gwsynthesis/leds.vg
-p GW5A-25A-LQFP144-1
-pn GW5A-LV25LQ144C1/I0
-cst /home/harbaum/projekte/private_stuff/mistlite/board/mistle_gw3a_20/tests/leds/leds.cst
-cfg /home/harbaum/projekte/private_stuff/mistlite/board/mistle_gw3a_20/tests/leds/impl/pnr/device.cfg
-bit
-tr
-ph
-timing
-cst_error
-convert_sdp32_36_to_sdp16_18
-place_option 0
-route_option 0
-clock_route_order 0
-correct_hold 1
-route_maxfan 23
-global_freq 100.000
-enable_dsrm 0
